# Generated by Django 5.2.8 on 2025-11-12 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=100, verbose_name='Nombres')),
                ('nameLastName', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('userName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('cellphone', models.CharField(max_length=10, unique=True, verbose_name='Numero telefonico')),
                ('password', models.CharField(max_length=20, verbose_name='Contrasena')),
                ('confirmPasword', models.CharField(max_length=20, verbose_name='Confirmar contrasena')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lastname', models.CharField(max_length=255)),
                ('cellphone', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
