# Generated by Django 5.2.8 on 2025-11-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_cellphone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterUsers',
        ),
    ]
