# Generated by Django 5.2.8 on 2025-11-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_delete_registerusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
