# Generated by Django 5.2.8 on 2025-11-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_groups',
        ),
    ]
