# Generated by Django 5.2.8 on 2025-11-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Product Image')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('stock', models.IntegerField(verbose_name='Stock Quantity')),
                ('date_in', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
            ],
        ),
    ]
