# Generated by Django 5.2.8 on 2025-11-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_in',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date in'),
        ),
    ]
